<?php

return [
    'catalog' => [
        [
            'id' => 'iphone-16-pro',
            'name' => 'iPhone 16 Pro',
            'tagline' => 'Titanium. Camera Control. A18 Pro.',
            'value' => 'RM 5,499',
            'kind' => 'iphone',
            'rarity' => 'legendary',
            'weight' => 6,
            'accent' => '#c8b4ff',
        ],
        [
            'id' => 'macbook-air',
            'name' => 'MacBook Air',
            'tagline' => 'M3 chip. Silent. All-day battery.',
            'value' => 'RM 4,799',
            'kind' => 'macbook',
            'rarity' => 'legendary',
            'weight' => 5,
            'accent' => '#9ad7ff',
        ],
        [
            'id' => 'ipad-pro',
            'name' => 'iPad Pro',
            'tagline' => 'Ultra Retina XDR. Apple Pencil ready.',
            'value' => 'RM 4,199',
            'kind' => 'ipad',
            'rarity' => 'epic',
            'weight' => 8,
            'accent' => '#b8c0ff',
        ],
        [
            'id' => 'watch-ultra',
            'name' => 'Apple Watch Ultra',
            'tagline' => 'Titanium case. Oceanic endurance.',
            'value' => 'RM 3,499',
            'kind' => 'watch',
            'rarity' => 'epic',
            'weight' => 10,
            'accent' => '#ffb38a',
        ],
        [
            'id' => 'airpods-pro',
            'name' => 'AirPods Pro',
            'tagline' => 'Adaptive Audio. USB-C case.',
            'value' => 'RM 999',
            'kind' => 'airpods',
            'rarity' => 'rare',
            'weight' => 18,
            'accent' => '#f2f5ff',
        ],
        [
            'id' => 'voucher',
            'name' => 'Twiport Voucher',
            'tagline' => 'RM 200 to spend anywhere in the market.',
            'value' => 'RM 200',
            'kind' => 'voucher',
            'rarity' => 'rare',
            'weight' => 20,
            'accent' => '#f6d889',
        ],
        [
            'id' => 'miss',
            'name' => 'Almost!',
            'tagline' => 'So close. Spin, scratch or drop again.',
            'value' => 'Try again',
            'kind' => 'miss',
            'rarity' => 'common',
            'weight' => 33,
            'accent' => '#8b90a5',
        ],
    ],
];
